spring:
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: update
         naming:
           physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
           implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
   properties:
      hibernate:
         format_sql: true
         dialect: org.hibernate.dialect.MySQL8Dialect
         SQL: debug
         type:
            descriptor:
               sql: trace       
   datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/envelope
      username: remoto
      password: 
   thymeleaf:
      suffix: .html
   application: 
      name: Bootstrap Spring Boot